"""empty message

Revision ID: d62c27df5172
Revises: 
Create Date: 2019-09-19 09:23:55.229519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62c27df5172'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('last_login_ip', sa.String(length=20), nullable=True),
    sa.Column('last_login_time', sa.DATETIME(), nullable=True),
    sa.Column('created_time', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_time', sa.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='用户基础表'
    )
    op.create_index(op.f('ix_t_user_email'), 't_user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_user_email'), table_name='t_user')
    op.drop_table('t_user')
    # ### end Alembic commands ###
